version: '3.8'
services:
  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile
      args:
        - ENV=production
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=prod-postgres
      - REDIS_HOST=prod-redis

  web:
    build: 
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        - ENV=production
    ports:
      - "3000:3000"

  docs:
    build: 
      context: ./apps/docs
      dockerfile: Dockerfile
      args:
        - ENV=production
    ports:
      - "3001:3001"